import type { Metadata } from "next";
// import { Inter } from "next/font/google"; // Удаляем Inter
import { GeistSans } from 'geist/font/sans'; // Импортируем GeistSans
import { GeistMono } from 'geist/font/mono';   // Импортируем GeistMono
import "./globals.css";
import SessionProviderWrapper from "@/components/SessionProviderWrapper";

// const inter = Inter({ subsets: ["latin"] }); // Удаляем Inter

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}> {/* Применяем переменные шрифтов Geist */}
      {/* <body className={inter.className}> Старый вариант с Inter */}
      <body> {/* Tailwind будет использовать --font-sans (Geist Sans) по умолчанию */}
        <SessionProviderWrapper>
          {children}
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
